#!/bin/sh

set -ex

echo "Creating bitcoin.conf"

apk upgrade bitcoin bitcoin-cli #upgrade bitcoin node

# Seed a random password for JSON RPC server
cat <<EOF > /etc/bitcoin.conf
printtoconsole=1
rpcuser=${RPCUSER:-bitcoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
EOF

cat /etc/bitcoin.conf

echo "Initialization completed successfully"

bitcoind -datadir=/bitcoin -rpcbind=0.0.0.0 -rpcallowip=::/0 -conf=/etc/bitcoin.conf